Fixup SUPATH in the installed image Allow setting some NIC properties on the installed image. Allow site-specific sysinstall.conf file.

diff --git a/components/openindiana/sysinstall/sysinstall_src/setup_autoinstall b/components/openindiana/sysinstall/sysinstall_src/setup_autoinstall
--- a/components/openindiana/sysinstall/sysinstall_src/setup_autoinstall
+++ b/components/openindiana/sysinstall/sysinstall_src/setup_autoinstall
@@ -15,6 +15,13 @@
 
 PKG_IMG_ROOT=$1
 
+if [ ! -f /usr/share/sysinstall/sysinstall.conf ]
+then
+	echo "/usr/share/sysinstall/sysinstall.conf Not Found!"
+	echo "Please create a site config from /usr/share/sysinstall/sysinstall.conf.default"
+	exit 1
+fi
+
 . /usr/share/sysinstall/sysinstall.conf
 /usr/share/sysinstall/cleanup_pkg_img $PKG_IMG_ROOT
 
