A bunhc of more fixes and tweaks to sysinstall utility.

diff --git a/components/openindiana/sysinstall/sysinstall_src/setup_autoinstall b/components/openindiana/sysinstall/sysinstall_src/setup_autoinstall
--- a/components/openindiana/sysinstall/sysinstall_src/setup_autoinstall
+++ b/components/openindiana/sysinstall/sysinstall_src/setup_autoinstall
@@ -18,6 +18,7 @@ PKG_IMG_ROOT=$1
 . /usr/share/sysinstall/sysinstall.conf
 /usr/share/sysinstall/cleanup_pkg_img $PKG_IMG_ROOT
 
+ds_copied=0
 mkdir -p $PKG_IMG_ROOT/local_config/
 for ds_spec in $ZFS_DATASET_LIST
 do
@@ -27,18 +28,22 @@ do
 	IFS="$_OIFS"
 	ds=$1
 
-	echo "Copying dataset $ds into PKG image area"
-	cp $ZFS_DATASET_IMAGES/$ds $PKG_IMG_ROOT/local_config/
-	if [ $? -ne 0 ]
+	if [ -f $ZFS_DATASET_IMAGES/$ds ]
 	then
-		echo "Error copying dataset $ds"
-		exit 1
+		echo "Copying dataset $ds into PKG image area"
+		cp $ZFS_DATASET_IMAGES/$ds $PKG_IMG_ROOT/local_config/
+		if [ $? -ne 0 ]
+		then
+			echo "Error copying dataset $ds"
+			exit 1
+		fi
+		ds_copied=1
 	fi
 done
 
-cp /usr/share/sysinstall/sysinstall.conf $PKG_IMG_ROOT/local_config/
+[ $ds_copied -eq 1 ] && cp /usr/share/sysinstall/sysinstall.conf $PKG_IMG_ROOT/local_config/
 
 #
 # Indicate that this is an automated install image
 #
-touch $PKG_IMG_ROOT/usr/share/auto_install
+touch $PKG_IMG_ROOT/usr/share/auto_sysinstall
